{"name": "test_login_failure[chromium-rty-vr4r-Invalid credentials. Please try again.]", "status": "passed", "parameters": [{"name": "browser_name", "value": "'chromium'"}, {"name": "username", "value": "'rty'"}, {"name": "password", "value": "'vr4r'"}, {"name": "result", "value": "'Invalid credentials. Please try again.'"}], "start": 1738128976179, "stop": 1738128980889, "uuid": "b619e29d-837e-4e22-b39f-2bfd3c09970b", "historyId": "1b631f0cee5da529f851434cd5038ad8", "testCaseId": "68772be64bb38f6a4c2b59109d7c35bc", "fullName": "test_login#test_login_failure", "labels": [{"name": "suite", "value": "test_login"}, {"name": "host", "value": "DESKTOP-TR3R9M3"}, {"name": "thread", "value": "45532-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_login"}]}